# Generated by Django 5.1.3 on 2024-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cards', 'Картой'), ('cash', 'Наличные')], default='cash', max_length=40, verbose_name='Тип оплаты'),
        ),
    ]
